name: Build theme
on:
  push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set node version
        run: echo "NODE_VERSION=$(cat .node-version)" >> $GITHUB_ENV
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: npm install
      - name: Install gulp
        run: npm install -g gulp
      - name: Build theme
        run: gulp build
